=== Leonora20/WebTech/xml_1705/e_test3/e_test3.xsd
<?xml version="1.0"?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.unigoa.ac.in/e_test3"            xmlns="http://www.unigoa.ac.in/e_test3" elementFormDefault="qualified">
 
  <!-- candidateStructureType++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <xs:simpleType name="genderType"> 
      <xs:restriction base="xs:string">
                <xs:pattern value="M|F"/> 
      </xs:restriction> 
  </xs:simpleType>


    <xs:simpleType name="ageType">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="60"/>
      </xs:restriction>
    </xs:simpleType>

  <xs:complexType name="flagType">
       <xs:simpleContent> 
                 <xs:extension base="xs:string"> 
                           <xs:attribute name="gender" type="genderType" use="required"/>
                 </xs:extension> 
        </xs:simpleContent>  
  </xs:complexType>

    <xs:simpleType name="cnameType">
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{1}([a-z])*"/>
      </xs:restriction>
    </xs:simpleType>


  <xs:simpleType name="cidType"> 
       <xs:restriction base="xs:string"> 
                <xs:pattern value="[a-z]{1}"/> 
       </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="cpartyType"> 
       <xs:restriction base="xs:string"> 
                <xs:pattern value="[a-z]{3}"/> 
       </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="candidateType"> 
     <xs:sequence> 
             <xs:element name="age" type="ageType" minOccurs="0" maxOccurs="unbounded"/>
             <xs:element name="flag" type="flagType" minOccurs="0" maxOccurs="unbounded"/>
             <xs:element name="cname" type="cnameType" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
                       <xs:attribute name="cid" type="cidType" use="required" />
                       <xs:attribute name="cparty" type="cpartyType" use="required" />
  </xs:complexType> 

  <xs:complexType name="candidate-listType"> 
         <xs:sequence> 
              <xs:element name="candidate" type="candidateType" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence> 
  </xs:complexType>

<!-- electionElement+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <xs:element name="election"> 
         <xs:complexType> 
                 <xs:sequence> 
                        <xs:element name="candidate-list" type="candidate-listType"/>       
                  </xs:sequence>
         </xs:complexType>
        
  </xs:element>

</xs:schema>

=== Leonora20/WebTech/xml_1705/e_test3/e_test3.xml
<?xml version="1.0"?>

<election xmlns="http://www.unigoa.ac.in/e_test3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.unigoa.ac.in/e_test3 e_test3.xsd">

	<candidate-list>
		<candidate cid="a" cparty="bjp">
			<age>30</age>
			<flag gender="M" />
			<cname>Alpha</cname>
		</candidate>
		<candidate cid="b" cparty="con">
			<age>30</age>
			<flag gender="M" />
			<cname>Beta</cname>
		</candidate>
		<candidate cid="z" cparty="aap">
			<age>30</age>
			<flag gender="M" />
			<cname>Zeta</cname>
		</candidate>
		<candidate cid="e" cparty="bjp">
			<age>30</age>
			<flag gender="M" />
			<cname>Epsilon</cname>
		</candidate>
		<candidate cid="d" cparty="con">
			<age>30</age>
			<flag gender="M" />
			<cname>Delta</cname>
		</candidate>
		<candidate cid="t" cparty="aap">
			<age>30</age>
			<flag gender="M" />
			<cname>Theta</cname>
		</candidate>
	</candidate-list>

</election>
