=== Leonora20/WebTech/xml_1705/e_test2/e_test2.xsd
<?xml version="1.0"?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.unigoa.ac.in/e_test2"            xmlns="http://www.unigoa.ac.in/e_test2" elementFormDefault="qualified">
 
<!-- partyListType+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <!-- constituencyListType+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <xs:simpleType name="gidType"> 
      <xs:restriction base="xs:string">
                <xs:pattern value="[a-z]{2}"/> 
      </xs:restriction> 
  </xs:simpleType>

  <xs:complexType name="nameType">
       <xs:simpleContent> 
                 <xs:extension base="xs:string"> 
                           <xs:attribute name="gid" type="gidType" use="required"/>
                 </xs:extension> 
        </xs:simpleContent>  
  </xs:complexType>
 
  <xs:simpleType name="conidType"> 
       <xs:restriction base="xs:string"> 
                <xs:pattern value="[a-z]{2}"/> 
       </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="votersType"> 
       <xs:restriction base="xs:integer"> 
                <xs:pattern value="[0-9]{6}"/> 
       </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="constituencyType"> 
     <xs:sequence> 
             <xs:element name="name" type="nameType" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
                       <xs:attribute name="conid" type="conidType" use="required" />
                       <xs:attribute name="voters" type="votersType" use="required" />
  </xs:complexType> 

  <xs:complexType name="constituency-listType"> 
         <xs:sequence> 
              <xs:element name="constituency" type="constituencyType" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence> 
  </xs:complexType>

<!-- electionElement+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <xs:element name="election"> 
         <xs:complexType> 
                 <xs:sequence> 
                        <!--<xs:element name="party-list" type="party-listType"/>    -->
                        <xs:element name="constituency-list" type="constituency-listType"/>           
                  </xs:sequence>
         </xs:complexType>
        
  </xs:element>

</xs:schema>

=== Leonora20/WebTech/xml_1705/e_test2/e_test2.xml
<?xml version="1.0"?>

<election xmlns="http://www.unigoa.ac.in/e_test2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.unigoa.ac.in/e_test2 e_test2.xsd">

	<constituency-list>
		<constituency conid="ng" voters="515441">
			<name gid="ma">Mandrem</name>
			<name gid="pe">Pernem</name>
			<name gid="bi">Bicholim</name>
			<name gid="ti">Tivim</name>
			<name gid="mp">Mapusa</name>
			<name gid="si">Siolim</name>
			<name gid="sa">Saligao</name>
			<name gid="ca">Canlagute</name>
			<name gid="po">Porvorim</name>
			<name gid="al">Aldona</name>
		</constituency>	
		<constituency conid="sg" voters="545336">
			<name gid="pn">Ponda</name>
			<name gid="sh">Shiroda</name>
			<name gid="mc">Marcaim</name>
			<name gid="mr">Marmugao</name>
			<name gid="vg">Vasco-Da-Gama</name>
			<name gid="co">Cortalim</name>
			<name gid="nu">Nuvem</name>
			<name gid="da">Dabolim</name>
			<name gid="cu">Curtorim</name>
			<name gid="fa">Fatorda</name>
		</constituency>	
	</constituency-list>

</election>
